# Generated by Django 6.0.7 on 2026-08-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
    ]
